---
- name: Snap service
  apt:
    name: snapd
    state: present

- name: General apps from snap
  command: snap install {{ item }}
  with_items:
    - spotify

-name: Classic snaps
  command: snap install {{ item }} --classic
  with_items:
    - skype