---

- name: Add virtual box repo
  become: true
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ubuntu_dist.stdout}} contrib

- name: Install key
  apt-key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Install virtual box
  become: true
  apt:
    update_cache: yes
    name:
      - virtualbox-5.2
      - dkms
    state: present