---
- name: Check nvm install
  stat: 
    path: /home/{{ ansible_user_id }}/.nvm/nvm.sh
  register: nvmStatus

- name: Get nvm install script
  get_url: 
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm.version  }}/install.sh 
    dest: /tmp/nvm-install.sh
    mode: 0740
  when: nvmStatus.stat.exists == False

- name: Install nvm
  shell: /tmp/nvm-install.sh
  args:
    creates: /home/{{ ansible_user_id }}/.nvm/alias
    executable: /bin/bash

- name: Install node
  shell: . ~/.nvm/nvm.sh && nvm install node {{ node.version }}
  args:
    creates: /home/{{ ansible_user_id }}/.nvm/versions/node/{{ node.version }}
    executable: /bin/bash

- name: Use installed version of node
  shell: source ~/.nvm/nvm.sh && nvm use {{ node.version }}
  args:
    executable: /bin/bash
    
- name: Set default version of node
  shell: source ~/.nvm/nvm.sh && nvm alias default {{ node.version }}
  args:
    executable: /bin/bash
